name = "Bluffy"
license = "MIT"
licenselink = "https://github.com/bluffy/hugo-bluffy-theme/blob/master/LICENSE"
description = "A CSS only theme"
homepage = "//github.com/bluffy/hugo-bluffy-theme"
tags = ["blog", "company", "projects", "minimal", "responsive"]
features = ["blog", "themes", "minimal", "responsive"]
min_version = 0.1

[author]
    name = "Mario"
    homepage = "//github.com/bluffy"
