baseurl = "https://example.org"
title = "Bluffy Basic"
theme = "hugo-bluffy-theme"
themesDir = "../.."
languageCode = "en-us"

defaultContentLanguage = "en"


[menu]

# Main menu

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier="blog"
    name = "Blog"
    url  = "/blog/"
    weight = 2

[[menu.main]]
    identifier = "faq"
    name = "FAQ"
    url  = "/faq/"
    weight = 3

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url  = "/contact/"
    weight = 4